//! Integration tests for `openapi3-rs`.
//!
//! Two test functions:
//! - `roundtrip_full_coverage` — constructs a document exercising **every type**
//!   and feature in the crate, then round-trips through JSON.
//! - `validate_against_swagger_validator` — a valid subset that passes the
//!   official Swagger validator (requires network; `#[ignore]` by default).
//!
//! Run with:
//! ```bash
//! cargo test                          # local tests
//! cargo test -- --ignored             # includes network-dependent validation
//! ```

use indexmap::IndexMap;
use openapi3_rs::*;
use schemars::JsonSchema;
use serde_json::{Map as JsonMap, Value};

// ---------------------------------------------------------------------------
// Test struct with schemars-derive for generated schema
// ---------------------------------------------------------------------------

#[derive(Debug, JsonSchema)]
#[allow(dead_code)]
struct NewPet {
    /// Name of the pet
    name: String,
    /// Tag / category
    #[schemars(default)]
    tag: Option<String>,
}

// ---------------------------------------------------------------------------
// Helper: convert a schemars::Schema into our Schema type
// ---------------------------------------------------------------------------

fn from_schemars(s: schemars::Schema) -> Schema {
    let value = s.to_value();
    serde_json::from_value(value).expect("schemars::Schema -> openapi3_rs::Schema")
}

// ---------------------------------------------------------------------------
// JSON response helper
// ---------------------------------------------------------------------------

fn json_response(desc: &str, schema_ref: &str) -> Response {
    Response {
        description: desc.into(),
        content: Some({
            let mut c = IndexMap::new();
            c.insert("application/json".into(), RefOr::Item(MediaType {
                schema: Some(RefOr::Item(Schema::Object(SchemaObject {
                    schema_data: {
                        let mut m = JsonMap::new();
                        m.insert("$ref".into(), Value::String(schema_ref.into()));
                        m
                    },
                    ..Default::default()
                }))),
                ..Default::default()
            }));
            c
        }),
        ..Default::default()
    }
}

// =========================================================================
//  build_full_coverage  —  exercises EVERY type and feature in the crate
// =========================================================================

fn build_full_coverage() -> OpenAPI {
    let generated_schema = schemars::schema_for!(NewPet);

    // -- Schemas: Bool, Object, discriminator, xml, externalDocs, example -----
    let mut schemas = IndexMap::new();

    // Boolean schema (true)
    schemas.insert("AllowAll".into(), Schema::Bool(true));

    // Boolean schema (false)
    schemas.insert("AllowNone".into(), Schema::Bool(false));

    // Pet with typed OAS fields
    schemas.insert("Pet".into(), Schema::Object(SchemaObject {
        discriminator: Some(Discriminator {
            property_name: "petType".into(),
            mapping: Some({
                let mut m = IndexMap::new();
                m.insert("cat".into(), "#/components/schemas/Cat".into());
                m.insert("dog".into(), "Dog".into());
                m
            }),
            default_mapping: Some("GenericPet".into()),
            ..Default::default()
        }),
        xml: Some(XML {
            name: Some("Pet".into()),
            namespace: Some("https://example.com/petstore".into()),
            prefix: Some("ps".into()),
            attribute: None,
            wrapped: None,
            node_type: Some(XmlNodeType::Element),
            ..Default::default()
        }),
        external_docs: Some(ExternalDocumentation {
            description: Some("More about Pet".into()),
            url: "https://example.com/docs/pet".into(),
            ..Default::default()
        }),
        schema_data: {
            let mut m = JsonMap::new();
            m.insert("examples".into(), serde_json::json!([{"id": 1, "name": "Fluffy"}]));
            m.insert("type".into(), "object".into());
            m.insert("required".into(), Value::Array(vec!["id".into(), "name".into()]));
            m.insert("properties".into(), serde_json::json!({
                "id":   { "type": "integer", "format": "int64" },
                "name": { "type": "string" },
            }));
            m
        },
        #[allow(deprecated)]
        example: None,
    }));

    // NewPet (generated by schemars)
    schemas.insert("NewPet".into(), from_schemars(generated_schema));

    // Error
    schemas.insert("Error".into(), Schema::Object(SchemaObject {
        schema_data: {
            let mut m = JsonMap::new();
            m.insert("type".into(), "object".into());
            m.insert("required".into(), Value::Array(vec!["code".into(), "message".into()]));
            m.insert("properties".into(), serde_json::json!({
                "code":    { "type": "integer", "format": "int32" },
                "message": { "type": "string" },
            }));
            m
        },
        ..Default::default()
    }));

    // GenericPet (default mapping target from discriminator)
    schemas.insert("GenericPet".into(), Schema::Object(SchemaObject {
        schema_data: {
            let mut m = JsonMap::new();
            m.insert("type".into(), "object".into());
            m.insert("properties".into(), serde_json::json!({
                "petType": { "type": "string" },
            }));
            m
        },
        ..Default::default()
    }));

    // -- Components: ALL fields -----------------------------------------------
    let mut components = Components::new();

    components.schemas = Some(schemas);

    // Reusable response
    components.responses = Some({
        let mut r = IndexMap::new();
        r.insert("NotFound".into(), RefOr::Item(Response {
            description: "Entity not found.".into(),
            ..Default::default()
        }));
        r
    });

    // Reusable parameter
    components.parameters = Some({
        let mut p = IndexMap::new();
        p.insert("offsetParam".into(), RefOr::Item(Parameter {
            name: "offset".into(),
            location: ParameterIn::Query,
            description: Some("Number of items to skip".into()),
            schema: Some(RefOr::Item(Schema::Object(SchemaObject {
                schema_data: {
                    let mut m = JsonMap::new();
                    m.insert("type".into(), "integer".into());
                    m.insert("format".into(), "int32".into());
                    m.insert("default".into(), 0.into());
                    m
                },
                ..Default::default()
            }))),
            ..Default::default()
        }));
        p
    });

    // Reusable example
    components.examples = Some({
        let mut e = IndexMap::new();
        e.insert("CatExample".into(), RefOr::Item(Example {
            summary: Some("A cat".into()),
            data_value: Some(serde_json::json!({"id": 2, "name": "Whiskers"})),
            serialized_value: None,
            external_value: None,
            value: None,
            description: None,
            ..Default::default()
        }));
        e
    });

    // Reusable request body
    components.request_bodies = Some({
        let mut b = IndexMap::new();
        b.insert("PetBody".into(), RefOr::Item(RequestBody {
            description: Some("Pet object".into()),
            required: Some(true),
            content: {
                let mut c = IndexMap::new();
                c.insert("application/json".into(), RefOr::Item(MediaType {
                    schema: Some(RefOr::Item(Schema::Object(SchemaObject {
                        schema_data: {
                            let mut m = JsonMap::new();
                            m.insert("$ref".into(), "#/components/schemas/NewPet".into());
                            m
                        },
                        ..Default::default()
                    }))),
                    ..Default::default()
                }));
                c
            },
            ..Default::default()
        }));
        b
    });

    // Reusable header
    components.headers = Some({
        let mut h = IndexMap::new();
        h.insert("X-Rate-Limit".into(), RefOr::Item(Header {
            description: Some("Rate limit remaining".into()),
            required: Some(false),
            schema: Some(RefOr::Item(Schema::Object(SchemaObject {
                schema_data: {
                    let mut m = JsonMap::new();
                    m.insert("type".into(), "integer".into());
                    m
                },
                ..Default::default()
            }))),
            ..Default::default()
        }));
        h
    });

    // Security schemes: apiKey + oauth2
    components.security_schemes = Some({
        let mut s = IndexMap::new();
        s.insert("api_key".into(), RefOr::Item(SecurityScheme {
            scheme_type: SecuritySchemeType::ApiKey,
            name: Some("X-API-Key".into()),
            location: Some(ApiKeyLocation::Header),
            description: Some("API Key authentication".into()),
            ..Default::default()
        }));
        s.insert("petstore_oauth".into(), RefOr::Item(SecurityScheme {
            scheme_type: SecuritySchemeType::Oauth2,
            description: Some("OAuth2 authentication".into()),
            flows: Some(OAuthFlows {
                implicit: Some(OAuthFlow {
                    authorization_url: Some("https://example.com/oauth/dialog".into()),
                    scopes: {
                        let mut sc = IndexMap::new();
                        sc.insert("write:pets".into(), "modify pets".into());
                        sc.insert("read:pets".into(), "read pets".into());
                        sc
                    },
                    ..Default::default()
                }),
                authorization_code: Some(OAuthFlow {
                    authorization_url: Some("https://example.com/oauth/dialog".into()),
                    token_url: Some("https://example.com/oauth/token".into()),
                    scopes: {
                        let mut sc = IndexMap::new();
                        sc.insert("admin".into(), "full access".into());
                        sc
                    },
                    ..Default::default()
                }),
                device_authorization: Some(OAuthFlow {
                    device_authorization_url: Some("https://example.com/oauth/device".into()),
                    token_url: Some("https://example.com/oauth/token".into()),
                    scopes: IndexMap::new(),
                    ..Default::default()
                }),
                ..Default::default()
            }),
            ..Default::default()
        }));
        s
    });

    // Reusable link
    components.links = Some({
        let mut l = IndexMap::new();
        l.insert("GetPet".into(), RefOr::Item(Link {
            operation_id: Some("getPetById".into()),
            description: Some("Navigate to the pet".into()),
            parameters: Some({
                let mut p = IndexMap::new();
                p.insert("petId".into(), "$response.body#/id".into());
                p
            }),
            server: Some(Server::new("https://petstore.example.com/v1")),
            ..Default::default()
        }));
        l
    });

    // Reusable callback
    components.callbacks = Some({
        let mut cb = IndexMap::new();
        cb.insert("StatusCallback".into(), RefOr::Item(Callback::from([(
            "{$request.body#/callbackUrl}".into(),
            RefOr::Item(PathItem {
                post: Some(Operation {
                    summary: Some("Status update".into()),
                    responses: Responses {
                        responses: {
                            let mut r = IndexMap::new();
                            r.insert("200".into(), RefOr::Item(Response {
                                description: "Received".into(),
                                ..Default::default()
                            }));
                            r
                        },
                        ..Default::default()
                    },
                    ..Default::default()
                }),
                ..Default::default()
            }),
        )])));
        cb
    });

    // Reusable path item
    components.path_items = Some({
        let mut p = IndexMap::new();
        p.insert("HealthPath".into(), PathItem {
            get: Some(Operation {
                summary: Some("Health check".into()),
                operation_id: Some("healthCheck".into()),
                responses: Responses {
                    responses: {
                        let mut r = IndexMap::new();
                        r.insert("200".into(), RefOr::Item(Response {
                            description: "Healthy".into(),
                            ..Default::default()
                        }));
                        r
                    },
                    ..Default::default()
                },
                ..Default::default()
            }),
            ..Default::default()
        });
        p
    });

    // Reusable media type (3.2)
    components.media_types = Some({
        let mut mt = IndexMap::new();
        mt.insert("JsonPatch".into(), RefOr::Item(MediaType {
            schema: Some(RefOr::Item(Schema::Object(SchemaObject {
                schema_data: {
                    let mut m = JsonMap::new();
                    m.insert("type".into(), "array".into());
                    m.insert("items".into(), serde_json::json!({
                        "type": "object",
                        "properties": {
                            "op":    { "type": "string", "enum": ["add","remove","replace"] },
                            "path":  { "type": "string" },
                            "value": { "type": "string" },
                        },
                    }));
                    m
                },
                ..Default::default()
            }))),
            ..Default::default()
        }));
        mt
    });

    // -- Extensions on Components ---------------------------------------------
    // Note: Extensions aren't directly on Components struct since it uses typed
    // fields. We test extensions through an x- header below.

    // -- Paths: ALL HTTP methods + additionalOperations ------------------------
    let mut paths = IndexMap::new();

    // GET /pets — basic list with parameter references and reusable response
    paths.insert("/pets".into(), RefOr::Item(PathItem {
        summary: Some("Pet collection".into()),
        description: Some("Operations on the pet collection".into()),
        parameters: Some(vec![
            RefOr::Item(Parameter {
                name: "Accept-Language".into(),
                location: ParameterIn::Header,
                description: Some("Requested language".into()),
                schema: Some(RefOr::Item(Schema::Object(SchemaObject {
                    schema_data: {
                        let mut m = JsonMap::new();
                        m.insert("type".into(), "string".into());
                        m.insert("default".into(), "en".into());
                        m
                    },
                    ..Default::default()
                }))),
                ..Default::default()
            }),
        ]),
        get: Some(Operation {
            summary: Some("List all pets".into()),
            operation_id: Some("listPets".into()),
            tags: Some(vec!["pets".into()]),
            parameters: Some(vec![
                // query param with style/explode/allowReserved
                RefOr::Item(Parameter {
                    name: "filter".into(),
                    location: ParameterIn::Query,
                    description: Some("Filter by tag".into()),
                    style: Some(Style::Form),
                    explode: Some(true),
                    allow_reserved: Some(false),
                    schema: Some(RefOr::Item(Schema::Object(SchemaObject {
                        schema_data: {
                            let mut m = JsonMap::new();
                            m.insert("type".into(), "array".into());
                            m.insert("items".into(), serde_json::json!({"type":"string"}));
                            m
                        },
                        ..Default::default()
                    }))),
                    ..Default::default()
                }),
                // reference to reusable parameter
                RefOr::Ref(Reference::new("#/components/parameters/offsetParam")),
            ]),
            responses: Responses {
                default: Some(RefOr::Item(json_response("Unexpected error", "#/components/schemas/Error"))),
                responses: {
                    let mut r = IndexMap::new();
                    r.insert("200".into(), RefOr::Item(Response {
                        description: "A paged list of pets".into(),
                        headers: Some({
                            let mut h = IndexMap::new();
                            h.insert("X-Total-Count".into(), RefOr::Item(Header {
                                description: Some("Total number of pets".into()),
                                schema: Some(RefOr::Item(Schema::Object(SchemaObject {
                                    schema_data: {
                                        let mut m = JsonMap::new();
                                        m.insert("type".into(), "integer".into());
                                        m
                                    },
                                    ..Default::default()
                                }))),
                                ..Default::default()
                            }));
                            h.insert("X-Rate-Limit".into(),
                                RefOr::Ref(Reference::new("#/components/headers/X-Rate-Limit")));
                            h
                        }),
                        links: Some({
                            let mut ln = IndexMap::new();
                            ln.insert("GetPet".into(),
                                RefOr::Ref(Reference::new("#/components/links/GetPet")));
                            ln
                        }),
                        content: Some({
                            let mut c = IndexMap::new();
                            c.insert("application/json".into(), RefOr::Item(MediaType {
                                schema: Some(RefOr::Item(Schema::Object(SchemaObject {
                                    schema_data: {
                                        let mut m = JsonMap::new();
                                        m.insert("type".into(), "array".into());
                                        m.insert("items".into(),
                                            serde_json::json!({"$ref": "#/components/schemas/Pet"}));
                                        m
                                    },
                                    ..Default::default()
                                }))),
                                ..Default::default()
                            }));
                            c
                        }),
                        ..Default::default()
                    }));
                    r
                },
            },
            security: Some(vec![{
                let mut m = IndexMap::new();
                m.insert("api_key".into(), vec![]);
                m
            }]),
            ..Default::default()
        }),
        // PUT /pets — idempotent bulk
        put: Some(Operation {
            summary: Some("Replace all pets".into()),
            operation_id: Some("replacePets".into()),
            tags: Some(vec!["pets".into()]),
            responses: Responses {
                responses: {
                    let mut r = IndexMap::new();
                    r.insert("200".into(), RefOr::Item(json_response("Replaced", "#/components/schemas/Pet")));
                    r
                },
                ..Default::default()
            },
            ..Default::default()
        }),
        // POST /pets — create, uses reusable request body
        post: Some(Operation {
            summary: Some("Create a pet".into()),
            operation_id: Some("createPet".into()),
            tags: Some(vec!["pets".into()]),
            request_body: Some(RefOr::Ref(Reference::new("#/components/requestBodies/PetBody"))),
            responses: Responses {
                responses: {
                    let mut r = IndexMap::new();
                    r.insert("201".into(), RefOr::Item(Response {
                        description: "Pet created".into(),
                        ..Default::default()
                    }));
                    r
                },
                ..Default::default()
            },
            ..Default::default()
        }),
        // DELETE /pets
        delete: Some(Operation {
            summary: Some("Delete all pets".into()),
            operation_id: Some("deleteAllPets".into()),
            responses: Responses {
                responses: {
                    let mut r = IndexMap::new();
                    r.insert("204".into(), RefOr::Item(Response {
                        description: "Deleted".into(),
                        ..Default::default()
                    }));
                    r
                },
                ..Default::default()
            },
            deprecated: Some(true),
            ..Default::default()
        }),
        // OPTIONS /pets
        options: Some(Operation {
            summary: Some("CORS options".into()),
            operation_id: Some("optionsPets".into()),
            responses: Responses {
                responses: {
                    let mut r = IndexMap::new();
                    r.insert("204".into(), RefOr::Item(Response {
                        description: "No content".into(),
                        ..Default::default()
                    }));
                    r
                },
                ..Default::default()
            },
            ..Default::default()
        }),
        // HEAD /pets
        head: Some(Operation {
            summary: Some("Headers for pets".into()),
            operation_id: Some("headPets".into()),
            responses: Responses {
                responses: {
                    let mut r = IndexMap::new();
                    r.insert("200".into(), RefOr::Item(Response {
                        description: "OK".into(),
                        ..Default::default()
                    }));
                    r
                },
                ..Default::default()
            },
            ..Default::default()
        }),
        // additionalOperation — custom HTTP method
        additional_operations: Some({
            let mut a = IndexMap::new();
            a.insert("COPY".into(), Operation {
                summary: Some("Copy a pet".into()),
                operation_id: Some("copyPet".into()),
                responses: Responses {
                    responses: {
                        let mut r = IndexMap::new();
                        r.insert("200".into(), RefOr::Item(Response {
                            description: "Copied".into(),
                            ..Default::default()
                        }));
                        r
                    },
                    ..Default::default()
                },
                ..Default::default()
            });
            a
        }),
        // path-level servers override
        servers: Some(vec![Server {
            url: "https://pets.petstore.example.com".into(),
            description: Some("Pet-specific server".into()),
            name: Some("petServer".into()),
            variables: None,
            ..Default::default()
        }]),
        ..Default::default()
    }));

    // GET /pets/{petId} — path param, cookie param, multiple response codes
    paths.insert("/pets/{petId}".into(), RefOr::Item(PathItem {
        get: Some(Operation {
            summary: Some("Get a pet by ID".into()),
            operation_id: Some("getPetById".into()),
            tags: Some(vec!["pets".into()]),
            parameters: Some(vec![
                RefOr::Item(Parameter {
                    name: "petId".into(),
                    location: ParameterIn::Path,
                    required: Some(true),
                    schema: Some(RefOr::Item(Schema::Object(SchemaObject {
                        schema_data: {
                            let mut m = JsonMap::new();
                            m.insert("type".into(), "integer".into());
                            m.insert("format".into(), "int64".into());
                            m
                        },
                        ..Default::default()
                    }))),
                    ..Default::default()
                }),
                // cookie param with cookie style
                RefOr::Item(Parameter {
                    name: "session".into(),
                    location: ParameterIn::Cookie,
                    style: Some(Style::Cookie),
                    explode: Some(true),
                    schema: Some(RefOr::Item(Schema::Bool(true))),
                    ..Default::default()
                }),
            ]),
            callbacks: Some({
                let mut cb = IndexMap::new();
                cb.insert("StatusCallback".into(),
                    RefOr::Ref(Reference::new("#/components/callbacks/StatusCallback")));
                cb
            }),
            external_docs: Some(ExternalDocumentation {
                url: "https://example.com/docs/get-pet".into(),
                description: None,
                ..Default::default()
            }),
            responses: Responses {
                // reference to reusable response
                default: Some(RefOr::Ref(Reference::new("#/components/responses/NotFound"))),
                responses: {
                    let mut r = IndexMap::new();
                    r.insert("200".into(), RefOr::Item(json_response("Pet found", "#/components/schemas/Pet")));
                    r.insert("4XX".into(), RefOr::Item(json_response("Client error", "#/components/schemas/Error")));
                    r
                },
            },
            ..Default::default()
        }),
        // PATCH /pets/{petId}
        patch: Some(Operation {
            summary: Some("Update a pet".into()),
            operation_id: Some("updatePet".into()),
            request_body: Some(RefOr::Item(RequestBody {
                content: {
                    let mut c = IndexMap::new();
                    c.insert("application/json-patch+json".into(), RefOr::Item(MediaType {
                        schema: Some(RefOr::Item(Schema::Object(SchemaObject {
                            schema_data: {
                                let mut m = JsonMap::new();
                                m.insert("$ref".into(), "#/components/mediaTypes/JsonPatch".into());
                                m
                            },
                            ..Default::default()
                        }))),
                        ..Default::default()
                    }));
                    c
                },
                ..Default::default()
            })),
            responses: Responses {
                responses: {
                    let mut r = IndexMap::new();
                    r.insert("200".into(), RefOr::Item(json_response("Updated", "#/components/schemas/Pet")));
                    r
                },
                ..Default::default()
            },
            ..Default::default()
        }),
        ..Default::default()
    }));

    // GET /pets/{petId}/avatar — multipart + encoding + itemSchema
    paths.insert("/pets/{petId}/avatar".into(), RefOr::Item(PathItem {
        get: Some(Operation {
            summary: Some("Get pet avatar".into()),
            operation_id: Some("getPetAvatar".into()),
            responses: Responses {
                responses: {
                    let mut r = IndexMap::new();
                    r.insert("200".into(), RefOr::Item(Response {
                        description: "Avatar image".into(),
                        content: Some({
                            let mut c = IndexMap::new();
                            c.insert("image/png".into(), RefOr::Item(MediaType::default()));
                            c
                        }),
                        ..Default::default()
                    }));
                    r
                },
                ..Default::default()
            },
            ..Default::default()
        }),
        // POST multipart upload with encoding
        post: Some(Operation {
            summary: Some("Upload avatar".into()),
            operation_id: Some("uploadAvatar".into()),
            request_body: Some(RefOr::Item(RequestBody {
                required: Some(true),
                content: {
                    let mut c = IndexMap::new();
                    c.insert("multipart/form-data".into(), RefOr::Item(MediaType {
                        schema: Some(RefOr::Item(Schema::Object(SchemaObject {
                            schema_data: {
                                let mut m = JsonMap::new();
                                m.insert("type".into(), "object".into());
                                m.insert("properties".into(), serde_json::json!({
                                    "avatar": { "type": "string", "format": "binary" },
                                    "caption": { "type": "string" },
                                }));
                                m
                            },
                            ..Default::default()
                        }))),
                        encoding: Some({
                            let mut e = IndexMap::new();
                            e.insert("avatar".into(), Encoding {
                                content_type: Some("image/png, image/jpeg".into()),
                                ..Default::default()
                            });
                            e.insert("caption".into(), Encoding {
                                content_type: Some("text/plain".into()),
                                ..Default::default()
                            });
                            e
                        }),
                        ..Default::default()
                    }));
                    c
                },
                ..Default::default()
            })),
            responses: Responses {
                responses: {
                    let mut r = IndexMap::new();
                    r.insert("201".into(), RefOr::Item(Response {
                        description: "Avatar uploaded".into(),
                        ..Default::default()
                    }));
                    r
                },
                ..Default::default()
            },
            ..Default::default()
        }),
        ..Default::default()
    }));

    // GET /pets/stream — streaming sequential media type (itemSchema)
    paths.insert("/pets/stream".into(), RefOr::Item(PathItem {
        get: Some(Operation {
            summary: Some("Stream pets".into()),
            operation_id: Some("streamPets".into()),
            responses: Responses {
                responses: {
                    let mut r = IndexMap::new();
                    r.insert("200".into(), RefOr::Item(Response {
                        description: "Stream of pets".into(),
                        content: Some({
                            let mut c = IndexMap::new();
                            c.insert("application/jsonl".into(), RefOr::Item(MediaType {
                                item_schema: Some(RefOr::Item(Schema::Object(SchemaObject {
                                    schema_data: {
                                        let mut m = JsonMap::new();
                                        m.insert("$ref".into(), "#/components/schemas/Pet".into());
                                        m
                                    },
                                    ..Default::default()
                                }))),
                                ..Default::default()
                            }));
                            c
                        }),
                        ..Default::default()
                    }));
                    r
                },
                ..Default::default()
            },
            ..Default::default()
        }),
        ..Default::default()
    }));

    // Content-based parameter (in: querystring + content with application/json)
    paths.insert("/pets/search".into(), RefOr::Item(PathItem {
        get: Some(Operation {
            summary: Some("Search pets".into()),
            operation_id: Some("searchPets".into()),
            parameters: Some(vec![
                RefOr::Item(Parameter {
                    name: "query".into(),
                    location: ParameterIn::Querystring,
                    content: Some({
                        let mut c = IndexMap::new();
                        c.insert("application/json".into(), RefOr::Item(MediaType {
                            schema: Some(RefOr::Item(Schema::Object(SchemaObject {
                                schema_data: {
                                    let mut m = JsonMap::new();
                                    m.insert("type".into(), "object".into());
                                    m.insert("properties".into(), serde_json::json!({
                                        "name": { "type": "string" },
                                        "tag":  { "type": "string" },
                                    }));
                                    m
                                },
                                ..Default::default()
                            }))),
                            ..Default::default()
                        }));
                        c
                    }),
                    ..Default::default()
                }),
            ]),
            responses: Responses {
                responses: {
                    let mut r = IndexMap::new();
                    r.insert("200".into(), RefOr::Item(Response {
                        description: "Search results".into(),
                        content: Some({
                            let mut c = IndexMap::new();
                            c.insert("application/json".into(), RefOr::Item(MediaType {
                                schema: Some(RefOr::Item(Schema::Object(SchemaObject {
                                    schema_data: {
                                        let mut m = JsonMap::new();
                                        m.insert("type".into(), "array".into());
                                        m.insert("items".into(),
                                            serde_json::json!({"$ref": "#/components/schemas/Pet"}));
                                        m
                                    },
                                    ..Default::default()
                                }))),
                                examples: Some({
                                    let mut ex = IndexMap::new();
                                    ex.insert("cats".into(),
                                        RefOr::Ref(Reference::new("#/components/examples/CatExample")));
                                    ex
                                }),
                                ..Default::default()
                            }));
                            c
                        }),
                        ..Default::default()
                    }));
                    r
                },
                ..Default::default()
            },
            ..Default::default()
        }),
        ..Default::default()
    }));

    // -- Assemble -------------------------------------------------------------

    OpenAPI {
        openapi: "3.1.0".into(),
        info: Info {
            title: "Full Coverage API".into(),
            summary: Some("Exercises every type".into()),
            description: Some("Complete integration test".into()),
            terms_of_service: Some("https://example.com/terms/".into()),
            contact: Some(Contact {
                name: Some("Test Support".into()),
                url: Some("https://example.com/support".into()),
                email: Some("test@example.com".into()),
                ..Default::default()
            }),
            license: Some(License {
                name: "MIT".into(),
                identifier: Some("MIT".into()),
                url: Some("https://opensource.org/licenses/MIT".into()),
                ..Default::default()
            }),
            version: "1.0.0".into(),
            ..Default::default()
        },
        self_uri: Some("https://example.com/api/openapi.json".into()),
        json_schema_dialect: Some("https://spec.openapis.org/oas/3.1/dialect/base".into()),
        servers: Some(vec![
            Server {
                url: "https://{environment}.example.com/v1".into(),
                description: Some("Environment-specific server".into()),
                name: Some("primary".into()),
                variables: Some({
                    let mut v = IndexMap::new();
                    v.insert("environment".into(), ServerVariable {
                        default: "api".into(),
                        r#enum: Some(vec!["api".into(), "staging".into(), "dev".into()]),
                        description: Some("Deployment environment".into()),
                        ..Default::default()
                    });
                    v
                }),
                ..Default::default()
            },
            Server::default_local(),
        ]),
        paths: Some(paths),
        webhooks: Some({
            let mut w = IndexMap::new();
            w.insert("newPet".into(), PathItem {
                post: Some(Operation {
                    summary: Some("New pet webhook".into()),
                    request_body: Some(RefOr::Item(RequestBody {
                        content: {
                            let mut c = IndexMap::new();
                            c.insert("application/json".into(), RefOr::Item(MediaType {
                                schema: Some(RefOr::Item(Schema::Object(SchemaObject {
                                    schema_data: {
                                        let mut m = JsonMap::new();
                                        m.insert("$ref".into(), "#/components/schemas/Pet".into());
                                        m
                                    },
                                    ..Default::default()
                                }))),
                                ..Default::default()
                            }));
                            c
                        },
                        ..Default::default()
                    })),
                    responses: Responses {
                        responses: {
                            let mut r = IndexMap::new();
                            r.insert("200".into(), RefOr::Item(Response {
                                description: "Webhook acknowledged".into(),
                                ..Default::default()
                            }));
                            r
                        },
                        ..Default::default()
                    },
                    ..Default::default()
                }),
                ..Default::default()
            });
            w
        }),
        components: Some(components),
        security: Some(vec![{
            let mut s = IndexMap::new();
            s.insert("petstore_oauth".into(), vec!["read:pets".into(), "write:pets".into()]);
            s
        }]),
        tags: Some(vec![
            Tag {
                name: "pets".into(),
                summary: Some("Pet operations".into()),
                description: Some("Everything about your Pets".into()),
                external_docs: Some(ExternalDocumentation {
                    description: Some("Pet docs".into()),
                    url: "https://example.com/docs/pets".into(),
                    ..Default::default()
                }),
                parent: None,
                kind: Some("nav".into()),
                ..Default::default()
            },
            Tag {
                name: "internal".into(),
                parent: Some("pets".into()),
                kind: Some("audience".into()),
                ..Default::default()
            },
        ]),
        external_docs: Some(ExternalDocumentation {
            description: Some("Full API documentation".into()),
            url: "https://example.com/docs".into(),
            ..Default::default()
        }),
        ..Default::default()
    }
}

// =========================================================================
//  Tests
// =========================================================================

#[test]
fn roundtrip_full_coverage() {
    let api = build_full_coverage();
    let json = serde_json::to_string_pretty(&api).expect("serialize");
    let back: OpenAPI = serde_json::from_str(&json).expect("deserialize");

    // ---- Spot-check key features survived the roundtrip ----

    // Root fields
    assert_eq!(back.self_uri.as_deref(), Some("https://example.com/api/openapi.json"));
    assert!(back.json_schema_dialect.is_some());
    assert!(back.external_docs.is_some());
    assert!(back.webhooks.as_ref().unwrap().contains_key("newPet"));

    // Servers with variables
    let sv = &back.servers.as_ref().unwrap()[0];
    assert_eq!(sv.name.as_deref(), Some("primary"));
    let env = sv.variables.as_ref().unwrap().get("environment").unwrap();
    assert_eq!(env.default, "api");

    // Tags with 3.2 fields
    let tags = back.tags.as_ref().unwrap();
    assert_eq!(tags[0].kind.as_deref(), Some("nav"));
    assert_eq!(tags[1].parent.as_deref(), Some("pets"));

    // Global security
    let sec = back.security.as_ref().unwrap();
    assert!(sec[0].contains_key("petstore_oauth"));

    // Boolean schemas
    let comp = back.components.as_ref().unwrap();
    let schemas = comp.schemas.as_ref().unwrap();
    assert!(schemas["AllowAll"].is_bool());
    assert!(schemas["AllowNone"].is_bool());
    assert_eq!(schemas["AllowAll"].as_bool(), Some(true));
    assert_eq!(schemas["AllowNone"].as_bool(), Some(false));

    // Discriminator + XML + externalDocs + example on schema
    let pet_obj = schemas["Pet"].as_object().unwrap();
    assert!(pet_obj.discriminator.is_some());
    assert_eq!(pet_obj.discriminator.as_ref().unwrap().property_name, "petType");
    assert!(pet_obj.xml.is_some());
    assert!(pet_obj.external_docs.is_some());
    assert!(pet_obj.examples().is_some());

    // All Components sub-maps
    assert!(comp.responses.as_ref().unwrap().contains_key("NotFound"));
    assert!(comp.parameters.as_ref().unwrap().contains_key("offsetParam"));
    assert!(comp.examples.as_ref().unwrap().contains_key("CatExample"));
    assert!(comp.request_bodies.as_ref().unwrap().contains_key("PetBody"));
    assert!(comp.headers.as_ref().unwrap().contains_key("X-Rate-Limit"));
    assert!(comp.security_schemes.as_ref().unwrap().contains_key("api_key"));
    assert!(comp.security_schemes.as_ref().unwrap().contains_key("petstore_oauth"));
    assert!(comp.links.as_ref().unwrap().contains_key("GetPet"));
    assert!(comp.callbacks.as_ref().unwrap().contains_key("StatusCallback"));
    assert!(comp.path_items.as_ref().unwrap().contains_key("HealthPath"));
    assert!(comp.media_types.as_ref().unwrap().contains_key("JsonPatch"));

    // All HTTP methods on /pets
    let paths = back.paths.as_ref().unwrap();
    let pets = paths["/pets"].as_item().unwrap();
    assert!(pets.get.is_some());
    assert!(pets.put.is_some());
    assert!(pets.post.is_some());
    assert!(pets.delete.is_some());
    assert!(pets.options.is_some());
    assert!(pets.head.is_some());
    assert!(pets.additional_operations.as_ref().unwrap().contains_key("COPY"));
    assert!(pets.servers.is_some());
    assert!(pets.parameters.is_some());

    // Deprecated operation
    assert_eq!(pets.delete.as_ref().unwrap().deprecated, Some(true));

    // Parameter styles and locations
    let list_op = pets.get.as_ref().unwrap();
    let filter_param = list_op.parameters.as_ref().unwrap()[0].as_item().unwrap();
    assert_eq!(filter_param.style, Some(Style::Form));
    assert_eq!(filter_param.explode, Some(true));

    // Path param + cookie param + externalDocs on operation
    let pet_path = paths["/pets/{petId}"].as_item().unwrap();
    let get_op = pet_path.get.as_ref().unwrap();
    assert!(get_op.external_docs.is_some());
    let params = get_op.parameters.as_ref().unwrap();
    assert_eq!(params[0].as_item().unwrap().location, ParameterIn::Path);
    assert_eq!(params[1].as_item().unwrap().location, ParameterIn::Cookie);
    assert!(get_op.callbacks.is_some());

    // Querystring parameter with content
    let search = paths["/pets/search"].as_item().unwrap();
    let search_op = search.get.as_ref().unwrap();
    let qs = search_op.parameters.as_ref().unwrap()[0].as_item().unwrap();
    assert_eq!(qs.location, ParameterIn::Querystring);
    assert!(qs.content.is_some());

    // Streaming media type (itemSchema)
    let stream_path = paths["/pets/stream"].as_item().unwrap();
    let stream_op = stream_path.get.as_ref().unwrap();
    let stream_body = &stream_op.responses.responses["200"].as_item().unwrap();
    let stream_content = stream_body.content.as_ref().unwrap();
    assert!(stream_content["application/jsonl"].as_item().unwrap().item_schema.is_some());

    // Multipart encoding
    let avatar_path = paths["/pets/{petId}/avatar"].as_item().unwrap();
    let upload_op = avatar_path.post.as_ref().unwrap();
    let upload_body = upload_op.request_body.as_ref().unwrap().as_item().unwrap();
    let upload_content = upload_body.content["multipart/form-data"].as_item().unwrap();
    let enc = upload_content.encoding.as_ref().unwrap();
    assert!(enc.contains_key("avatar"));
    assert!(enc.contains_key("caption"));

    // References (round-trip survives $ref)
    let list_responses = &list_op.responses;
    assert!(list_responses.default.is_some());
    assert!(list_responses.responses["200"].as_item().unwrap().headers.is_some());

    // Security on operation
    assert!(list_op.security.is_some());

    // OAuth2 device_authorization flow (3.2)
    let oauth = comp.security_schemes.as_ref().unwrap()["petstore_oauth"]
        .as_item().unwrap();
    let flows = oauth.flows.as_ref().unwrap();
    assert!(flows.device_authorization.is_some());
    assert!(flows.implicit.is_some());

    // Reusable Example with dataValue
    let ex = comp.examples.as_ref().unwrap()["CatExample"].as_item().unwrap();
    assert!(ex.data_value.is_some());

    // Link with server
    let link = comp.links.as_ref().unwrap()["GetPet"].as_item().unwrap();
    assert!(link.server.is_some());
    assert!(link.parameters.is_some());

    // Callback roundtrip
    let cb = comp.callbacks.as_ref().unwrap()["StatusCallback"].as_item().unwrap();
    assert!(cb.contains_key("{$request.body#/callbackUrl}"));
}

#[test]
fn roundtrip_petstore() {
    let api = build_petstore();
    let json = serde_json::to_string_pretty(&api).expect("serialize");
    let _back: OpenAPI = serde_json::from_str(&json).expect("deserialize");
}

#[test]
fn validate_against_swagger_validator() {
    let api = build_petstore();
    let json = serde_json::to_string_pretty(&api).expect("serialize");

    let output = std::process::Command::new("curl")
        .args([
            "-s", "-X", "POST",
            "-H", "Content-Type: application/json",
            "-d", &json,
            "https://validator.swagger.io/validator/debug",
        ])
        .output()
        .expect("curl to validator");

    assert!(output.status.success(),
        "curl failed: {}", String::from_utf8_lossy(&output.stderr));

    let body: Value = serde_json::from_slice(&output.stdout)
        .expect("parse validator response");

    let errors = body.get("schemaValidationMessages")
        .and_then(|v| v.as_array())
        .map(|a| a.as_slice())
        .unwrap_or(&[]);

    if !errors.is_empty() {
        eprintln!("Validator returned {} error(s):", errors.len());
        for err in errors {
            eprintln!("  - {}", serde_json::to_string_pretty(err).unwrap());
        }
        eprintln!("\nSubmitted document:\n{json}");
    }

    assert!(errors.is_empty(),
        "OpenAPI document failed swagger validation with {} error(s)", errors.len());
}

// =========================================================================
//  build_petstore  —  validator-friendly subset
// =========================================================================

fn build_petstore() -> OpenAPI {
    let generated_schema = schemars::schema_for!(NewPet);

    let mut schemas = IndexMap::new();
    schemas.insert("Pet".into(), Schema::Object(SchemaObject {
        schema_data: {
            let mut m = JsonMap::new();
            m.insert("type".into(), "object".into());
            m.insert("required".into(), Value::Array(vec!["id".into(), "name".into()]));
            m.insert("properties".into(), serde_json::json!({
                "id":   { "type": "integer", "format": "int64" },
                "name": { "type": "string" },
                "tag":  { "type": "string" },
            }));
            m
        },
        ..Default::default()
    }));
    schemas.insert("NewPet".into(), from_schemars(generated_schema));
    schemas.insert("Error".into(), Schema::Object(SchemaObject {
        schema_data: {
            let mut m = JsonMap::new();
            m.insert("type".into(), "object".into());
            m.insert("required".into(), Value::Array(vec!["code".into(), "message".into()]));
            m.insert("properties".into(), serde_json::json!({
                "code":    { "type": "integer", "format": "int32" },
                "message": { "type": "string" },
            }));
            m
        },
        ..Default::default()
    }));

    let mut paths = IndexMap::new();

    paths.insert("/pets".into(), RefOr::Item(PathItem {
        get: Some(Operation {
            summary: Some("List all pets".into()),
            operation_id: Some("listPets".into()),
            tags: Some(vec!["pets".into()]),
            parameters: Some(vec![RefOr::Item(Parameter {
                name: "limit".into(),
                location: ParameterIn::Query,
                description: Some("Max pets to return".into()),
                schema: Some(RefOr::Item(Schema::Object(SchemaObject {
                    schema_data: {
                        let mut m = JsonMap::new();
                        m.insert("type".into(), "integer".into());
                        m.insert("format".into(), "int32".into());
                        m.insert("default".into(), 20.into());
                        m
                    },
                    ..Default::default()
                }))),
                ..Default::default()
            })]),
            responses: Responses {
                default: Some(RefOr::Item(json_response("Unexpected error", "#/components/schemas/Error"))),
                responses: {
                    let mut r = IndexMap::new();
                    r.insert("200".into(), RefOr::Item(Response {
                        description: "A paged list of pets".into(),
                        content: Some({
                            let mut c = IndexMap::new();
                            c.insert("application/json".into(), RefOr::Item(MediaType {
                                schema: Some(RefOr::Item(Schema::Object(SchemaObject {
                                    schema_data: {
                                        let mut m = JsonMap::new();
                                        m.insert("type".into(), "array".into());
                                        m.insert("items".into(),
                                            serde_json::json!({"$ref": "#/components/schemas/Pet"}));
                                        m
                                    },
                                    ..Default::default()
                                }))),
                                ..Default::default()
                            }));
                            c
                        }),
                        ..Default::default()
                    }));
                    r
                },
            },
            ..Default::default()
        }),
        post: Some(Operation {
            summary: Some("Create a pet".into()),
            operation_id: Some("createPet".into()),
            tags: Some(vec!["pets".into()]),
            request_body: Some(RefOr::Item(RequestBody {
                description: Some("The pet to create".into()),
                required: Some(true),
                content: {
                    let mut c = IndexMap::new();
                    c.insert("application/json".into(), RefOr::Item(MediaType {
                        schema: Some(RefOr::Item(Schema::Object(SchemaObject {
                            schema_data: {
                                let mut m = JsonMap::new();
                                m.insert("$ref".into(), "#/components/schemas/NewPet".into());
                                m
                            },
                            ..Default::default()
                        }))),
                        ..Default::default()
                    }));
                    c
                },
                ..Default::default()
            })),
            responses: Responses {
                responses: {
                    let mut r = IndexMap::new();
                    r.insert("201".into(), RefOr::Item(Response {
                        description: "Pet created successfully".into(),
                        ..Default::default()
                    }));
                    r.insert("default".into(), RefOr::Item(json_response("Error", "#/components/schemas/Error")));
                    r
                },
                ..Default::default()
            },
            ..Default::default()
        }),
        ..Default::default()
    }));

    paths.insert("/pets/{petId}".into(), RefOr::Item(PathItem {
        get: Some(Operation {
            summary: Some("Get a pet by ID".into()),
            operation_id: Some("getPetById".into()),
            tags: Some(vec!["pets".into()]),
            parameters: Some(vec![RefOr::Item(Parameter {
                name: "petId".into(),
                location: ParameterIn::Path,
                required: Some(true),
                schema: Some(RefOr::Item(Schema::Object(SchemaObject {
                    schema_data: {
                        let mut m = JsonMap::new();
                        m.insert("type".into(), "integer".into());
                        m.insert("format".into(), "int64".into());
                        m
                    },
                    ..Default::default()
                }))),
                ..Default::default()
            })]),
            responses: Responses {
                default: Some(RefOr::Item(json_response("Error", "#/components/schemas/Error"))),
                responses: {
                    let mut r = IndexMap::new();
                    r.insert("200".into(), RefOr::Item(json_response("Pet found", "#/components/schemas/Pet")));
                    r
                },
            },
            ..Default::default()
        }),
        ..Default::default()
    }));

    OpenAPI {
        openapi: "3.1.0".into(),
        info: Info {
            title: "Swagger Petstore".into(),
            summary: Some("A sample petstore API".into()),
            description: Some("Sample server for a pet store.".into()),
            terms_of_service: Some("https://example.com/terms/".into()),
            contact: Some(Contact {
                name: Some("API Support".into()),
                url: Some("https://www.example.com/support".into()),
                email: Some("support@example.com".into()),
                ..Default::default()
            }),
            license: Some(License {
                name: "Apache 2.0".into(),
                identifier: Some("Apache-2.0".into()),
                url: None,
                ..Default::default()
            }),
            version: "1.0.0".into(),
            ..Default::default()
        },
        servers: Some(vec![Server {
            url: "https://petstore.example.com/v1".into(),
            description: Some("Production server".into()),
            ..Default::default()
        }]),
        paths: Some(paths),
        components: Some(Components {
            schemas: Some(schemas),
            ..Default::default()
        }),
        tags: Some(vec![Tag {
            name: "pets".into(),
            description: Some("Everything about your Pets".into()),
            ..Default::default()
        }]),
        ..Default::default()
    }
}

